version: 1.0.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  TARGET_CONFIGURATION: Release
build_script:
- cmd: >-
    dotnet build -p:Version=%APPVEYOR_BUILD_VERSION% --configuration %TARGET_CONFIGURATION%

    appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%/SubstrateNetApi/bin/Release/SubstrateNetApi.%APPVEYOR_BUILD_VERSION%.nupkg -FileName SubstrateNetApi.%APPVEYOR_BUILD_VERSION%.nupkg -DeploymentName SubstrateNetApi
    
    appveyor PushArtifact %APPVEYOR_BUILD_FOLDER%/SubstrateNetWallet/bin/Release/SubstrateNetWallet.%APPVEYOR_BUILD_VERSION%.nupkg -FileName SubstrateNetWallet.%APPVEYOR_BUILD_VERSION%.nupkg -DeploymentName SubstrateNetWallet
    
test_script:
- cmd: >-
    dotnet test --configuration Release ./SubstrateNetApiTest
    
    dotnet test --configuration Release ./SubstrateNetWalletTest
    
deploy:
- provider: NuGet
  api_key:
    secure: CsUZhCNrxpwndMW1eqb3Cy0UdkDMOR+zjA9tnhe0ePq2569Vgp6r7p9xNpJ9Arr1
  artifact: /.*.nupkg/
